multiprocessing: False  # True
execute_code: True

dataset:
  data_path: /home/xueqing.wu/data/NExTVideo/
  #  data_path: /local/minh/VIPER/datasets/NExTVideo/csvs/  # minh
  dataset_name: NExTQA
  version: multiplechoice
  fps: 1
  max_num_frames: 30
  split: val
  batch_size: 1
  max_samples: 100

#codex:
#  prompt: ./prompts/benchmarks/nextqa.prompt
code_gen:
  model_class: openai
  specific_model: gpt-4o-mini-2024-07-18
  temperature: 1
  prompt: ./prompts/benchmarks/nextqa.chatprompt
  top_p: 0.9

select_answer_prompt: ./prompts/gpt3/video_question.txt
fixed_code_file: ./prompts/fixed_code/blip2_video.prompt

results_dir: ./results/nextqa/

gpt3:
  model: gpt-4o-mini-2024-07-18

use_cached_codex: True
cached_codex_path: results/nextqa/val/results_18.csv